/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import Cryptography.passwordEncryption;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thanglt
 */
public class Localgroup_Admin extends javax.swing.JFrame {

    private Statement stmt;
    private ResultSet rs;
    private Connection cn;
    private ResultSetMetaData rsmt;
    private PreparedStatement preparedStatement = null;
    passwordEncryption ps = new passwordEncryption();

    /**
     * Creates new form AddUserAdmin
     */
    public Localgroup_Admin() {
        ConnectDatabase.Connect kn = new ConnectDatabase.Connect();
        cn = kn.connected();
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Add User in LocalGroup Administrators");
        lb_date.setText("Date: " + new Date(Calendar.getInstance().getTime().getTime()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_password = new javax.swing.JPasswordField();
        tf_userName = new javax.swing.JTextField();
        bt_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typeManegement = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tf_fullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_description = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf_confimpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cb_useractive = new javax.swing.JCheckBox();
        cb_neverexpires = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        bt_comeback = new javax.swing.JButton();
        lb_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_submit.setText("Submit");
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name: ");

        jLabel2.setText("Password: ");

        typeManegement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator" }));

        jLabel3.setText("Type: ");

        jLabel4.setText("Full Name: ");

        jLabel5.setText("Description: ");

        jLabel6.setText("Confim Password: ");

        cb_useractive.setText("User will active");

        cb_neverexpires.setText("User never expires");

        bt_comeback.setText("< Back");
        bt_comeback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comebackActionPerformed(evt);
            }
        });

        lb_date.setText("Date: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_useractive)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_neverexpires)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_comeback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_submit))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_userName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_fullname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_description, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(typeManegement, javax.swing.GroupLayout.Alignment.TRAILING, 0, 259, Short.MAX_VALUE)
                                    .addComponent(tf_confimpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(tf_password, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeManegement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_confimpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_useractive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_neverexpires)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_submit)
                    .addComponent(bt_comeback)
                    .addComponent(lb_date))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        DefaultComboBoxModel model = (DefaultComboBoxModel) typeManegement.getModel();
        if (tf_userName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your USER NAME", "Notfitition", 1);
        }
        if (tf_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your PASSWORD", "Notfitition", 1);
        }
        if (!tf_password.getText().equals(tf_confimpassword.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter Confim Password equals Password", "Notfitition", 1);
        } else {

        }
    }//GEN-LAST:event_bt_submitActionPerformed

    private void bt_comebackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comebackActionPerformed
        Account ac = new Account();
        ac.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bt_comebackActionPerformed

    public void insertData(String username, String password, int active, String typeUser, java.sql.Date dateExpires, String dateSignIn) {
        try {
            String passWord = ps.MD5(password);
            preparedStatement = cn.prepareStatement("insert into user_manager values(default, ?, ?, ?, ?, ?)");

            preparedStatement.setString(1, username);
            preparedStatement.setString(2, passWord);
            preparedStatement.setInt(3, active);
            preparedStatement.setString(4, typeUser.toLowerCase());
            preparedStatement.setDate(5, dateExpires);
            preparedStatement.setDate(6, new Date(Calendar.getInstance().getTime().getTime()));

            preparedStatement.executeUpdate();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_comeback;
    private javax.swing.JButton bt_submit;
    private javax.swing.JCheckBox cb_neverexpires;
    private javax.swing.JCheckBox cb_useractive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_date;
    private javax.swing.JPasswordField tf_confimpassword;
    private javax.swing.JTextField tf_description;
    private javax.swing.JTextField tf_fullname;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_userName;
    private javax.swing.JComboBox typeManegement;
    // End of variables declaration//GEN-END:variables
}
